"""empty message

Revision ID: c240f911ba2e
Revises: 
Create Date: 2020-07-05 12:01:30.883951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c240f911ba2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profession_name'), 'profession', ['name'], unique=True)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('expirience', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_area'), 'vacancy', ['area'], unique=False)
    op.create_index(op.f('ix_vacancy_expirience'), 'vacancy', ['expirience'], unique=False)
    op.create_index(op.f('ix_vacancy_name'), 'vacancy', ['name'], unique=False)
    op.create_index(op.f('ix_vacancy_salary'), 'vacancy', ['salary'], unique=False)
    op.create_table('vacancy_skill',
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skill')
    op.drop_index(op.f('ix_vacancy_salary'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_name'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_expirience'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_area'), table_name='vacancy')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_profession_name'), table_name='profession')
    op.drop_table('profession')
    # ### end Alembic commands ###
